export default {
  "BLOCK_GENERATION_TIME": 3,
  "PIN_MAX_RETRY_COUNT": 3,
  "PRICE_POINT_CURRENCY_SYMBOL": "USD",
  "REQUEST_TIMEOUT_DURATION": 60,
  "SESSION_BUFFER_TIME":3600,
  "USE_SEED_PASSWORD": true,
  "NO_OF_SESSIONS_ON_ACTIVATE_USER": 5
}